engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.css"
  - "**.erb"
  - "**.haml"
  - "**.html"
  - "**.js"
  - "**.json"
  - "**.rake"
  - "**.rb"
  - "**.sass"
  - "**.yaml"
  - "**.yml"
  - Gemfile.lock
  - Gemfile
exclude_paths:
- config/
- db/
- spec/
- public/
- app/assets/stylesheets/bootstrap-accessibility.css
- app/assets/javascripts/bootstrap*
