---
fail_on_violations: true
ruby:
  config_file: .rubocop.yml
haml:
  config_file: .haml-lint.yml
scss:
  config_file: .scss-lint.yml
eslint:
  ignore_file: .eslintignore
  config_file: .eslintrc
jshint:
  enabled: false
