version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
workflows:
   version: 2
   fullbuild:
     jobs:
       - test
       - lint
       - contributors
jobs:
  contributors:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run:
          name: Check contributors
          command: bundle exec script/check_contributors_md.rb

  lint:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run:
          name: Upgrade bundler
          command: gem install bundler
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Linters
          command: ./script/check_static.rb
  test:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Create database
          command: bundle exec rails db:create db:migrate
          
      - run:
          name: Create database
          command: bundle exec rails db:create db:migrate

      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile

      - run:
          name: Create Elastic search index
          command: bundle exec rails search:reindex

      - run:
          name: Run rpsec tests
          command: bundle exec rspec spec
          
