version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
workflows:
  version: 2
  fullbuild:
    jobs:
      - test:
          requires:
            - rubydeps
      - lint:
          requires:
            - rubydeps
      - contributors
jobs:
  rubydeps:
    docker:
      - image: circleci/ruby:2.6.3-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ruby-deps-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run:
          name: Install dependencies
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: v1-ruby-deps-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  contributors:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run:
          name: Check contributors
          command: script/check_contributors_md.rb

  lint:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ruby-deps-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle check --path vendor/bundle || bundle install --deployment

      - run:
          name: Install linters
          command: ./scripts/install_linters.sh
      - run:
          name: Run overcommit
          command: overcommit --run
  test:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ruby-deps-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle check --path vendor/bundle || bundle install --deployment

      - run:
          name: Create database
          command: bundle exec rails db:create db:migrate
      - run:
          name: Create database
          command: bundle exec rails db:create db:migrate
      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile
      - run:
          name: Create Elastic search index
          command: bundle exec rails search:reindex
      - run:
          name: Run rpsec tests
          command: bundle exec rspec spec
